CREATE TABLE [sankhya].[TFPEVE](
	[CODEVENTO] [smallint] NOT NULL,
	[DESCREVENTO] [char](30) NOT NULL,
	[TIPEVENTO] [smallint] NOT NULL,
	[UNIDADE] [char](1) NOT NULL,
	[CODFORM] [smallint] NULL,
	[INDICE] [float] NULL,
	[VLREVENTO] [money] NULL,
	[IMPHOLLERIT] [char](1) NULL,
	[INCSOBREMEDIAS] [char](1) NULL,
	[BASEINFREND] [char](1) NOT NULL,
	[BASEMARGCONSIG] [char](1) NOT NULL,
	[PROTEGIDO] [char](1) NOT NULL,
	[SEQCALCULO] [float] NULL,
	[ACUMULADOR] [char](1) NOT NULL,
	[BASERAIS] [char](1) NOT NULL,
	[BASELIQUIDO] [char](1) NOT NULL,
	[FOLHA] [char](1) NOT NULL,
	[FERIAS] [char](1) NOT NULL,
	[RESCISAO] [char](1) NOT NULL,
	[DECTERC] [char](1) NOT NULL,
	[SEMANAL] [char](1) NOT NULL,
	[ADIANTAMENTO] [char](1) NOT NULL,
	[DTALTER] [datetime] NOT NULL,
	[CODUSU] [smallint] NULL,
	[DOCUMENTACAO] [text] NULL,
	[CODCENCUS] [int] NOT NULL,
	[CODNAT] [int] NOT NULL,
	[PROVISAOFIN] [smallint] NOT NULL,
	[PENSAO] [char](1) NOT NULL,
	[INCORPORA] [char](1) NOT NULL,
	[CODEVERESILICAO] [smallint] NULL,
	[RESILICAO] [char](1) NOT NULL,
	[COMPLEMENTORESC] [char](1) NOT NULL,
	[REGCALCULO] [char](1) NULL,
	[ATIVO] [char](1) NOT NULL,
	[SANKHYA] [char](1) NOT NULL,
	[IDENTIFICACAO] [smallint] NOT NULL,
	[TIPOINSS] [smallint] NOT NULL,
	[TIPOIRRF] [smallint] NOT NULL,
	[FGTS] [char](1) NOT NULL,
	[FGTSDECTERCEIRO] [char](1) NOT NULL,
	[BASEAUXILIAR] [char](1) NOT NULL,
	[PIS] [char](1) NOT NULL,
	[ISS] [char](1) NOT NULL,
	[INFCOMPLRAIS1] [smallint] NOT NULL,
	[INFCOMPLRAIS2] [smallint] NOT NULL,
	[GRRFMES] [char](1) NOT NULL,
	[GRRFMESANTERIOR] [char](1) NOT NULL,
	[GRRFINDENIZACAO] [char](1) NOT NULL,
	[BASESEFIP] [smallint] NOT NULL,
	[FGTSSEFIP] [char](1) NOT NULL,
	[INSSSEFIP] [char](1) NOT NULL,
	[CODEVECORRELATO] [smallint] NULL,
	[RUBRICAMTE] [smallint] NULL,
	[CODOUTRASMTE] [smallint] NULL,
	[INDICEADMEDIAS] [float] NULL,
	[USADOESOCIAL] [char](1) NOT NULL,
	[CODNATRUBRICA] [varchar](4) NULL,
	[CONTRIBSIND] [char](1) NOT NULL,
	[RUBRICADSR] [char](1) NOT NULL,
	[RUBRICA13] [char](1) NOT NULL,
	[RUBRICAFERIAS] [char](1) NOT NULL,
	[RUBRICARESCISAO] [char](1) NOT NULL,
	[TEMCOMPLEMENTO] [char](1) NOT NULL,
	[CODEVECOMPLEMENTO] [smallint] NULL,
	[COMPLEMENTAR] [char](1) NOT NULL,
	[PLR] [char](1) NOT NULL,
	[INTEGRACTB] [char](1) NOT NULL,
	[DSCSALVAR] [varchar](90) NULL,
	[FGTSRESCISAO] [char](1) NOT NULL,
	[CODCRIRATEIO] [smallint] NULL,
	[GRUPOMEDIAS] [varchar](20) NULL,
	[PENSAOSALLIQUIDO] [char](1) NOT NULL,
	[PENSAOSALBRUTO] [char](1) NOT NULL,
	[PENSAOSALMINIMO] [char](1) NOT NULL,
	[CODINCCP] [char](2) NULL,
	[CODINCIRRF] [varchar](4) NULL,
	[CODINCFGTS] [char](2) NULL,
	[CODINCSIND] [char](2) NULL,
	[GRUPOEVENTO] [int] NOT NULL,
	[PSEUDOCODEVENTO] [int] NULL,
	[CODMOEDA] [smallint] NULL,
	[USACODMOEDA] [char](1) NOT NULL,
	[INDENIZACAOAPI] [char](1) NOT NULL,
	[ATIVOW] [varchar](1) NOT NULL,
	[CHECKSUM] [varchar](64) NULL,
	[INTERMITENTE] [char](1) NOT NULL,
	[EVENTODSR] [char](1) NULL,
	[EVENTOFALTA] [char](1) NULL,
	[CODEVERRACPL] [smallint] NULL,
	[CODEVEFLRES] [varchar](1) NULL,
	[CONSPROGFER] [char](1) NOT NULL,
	[DIASCPROGFER] [int] NULL,
	[DTINATAPARDE] [datetime] NULL,
	[UTSALBASEARED] [varchar](1) NOT NULL,
	[CODEVEFLFER] [varchar](1) NOT NULL,
	[USALEI10820] [char](1) NOT NULL,
	[IGPMCOMISSAO] [smallint] NULL,
	[INPCCOMISSAO] [smallint] NULL,
	[REFLEXIVOS] [varchar](100) NULL,
	[PROVIDECTERSAL] [varchar](1) NULL,
	[PROVIFERIAS] [varchar](1) NULL,
	[DTATUALIZACAO] [datetime] NULL,
 CONSTRAINT [PK_TFPEVE] PRIMARY KEY CLUSTERED 
(
	[CODEVENTO] ASC)
GO

ALTER TABLE [sankhya].[TFPEVE] SET (LOCK_ESCALATION = DISABLE)
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF__TFPEVE__TIPEVENT__056ECC6A]  DEFAULT ((-1)) FOR [TIPEVENTO]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF__TFPEVE__UNIDADE__075714DC]  DEFAULT ('D') FOR [UNIDADE]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF__TFPEVE__IMPHOLLE__093F5D4E]  DEFAULT ('S') FOR [IMPHOLLERIT]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF__TFPEVE__INCSOBRE__0B27A5C0]  DEFAULT ('N') FOR [INCSOBREMEDIAS]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF__TFPEVE__BASEINFR__0D0FEE32]  DEFAULT ('N') FOR [BASEINFREND]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF__TFPEVE__BASEMARG__0EF836A4]  DEFAULT ('N') FOR [BASEMARGCONSIG]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF__TFPEVE__PROTEGID__10E07F16]  DEFAULT ('N') FOR [PROTEGIDO]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF__TFPEVE__ACUMULAD__12C8C788]  DEFAULT ('N') FOR [ACUMULADOR]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF__TFPEVE__BASERAIS__14B10FFA]  DEFAULT ('N') FOR [BASERAIS]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF__TFPEVE__BASELIQU__1699586C]  DEFAULT ('N') FOR [BASELIQUIDO]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF__TFPEVE__FOLHA__1881A0DE]  DEFAULT ('S') FOR [FOLHA]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF__TFPEVE__FERIAS__1A69E950]  DEFAULT ('N') FOR [FERIAS]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF__TFPEVE__RESCISAO__1C5231C2]  DEFAULT ('N') FOR [RESCISAO]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF__TFPEVE__DECTERC__1E3A7A34]  DEFAULT ('N') FOR [DECTERC]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF__TFPEVE__SEMANAL__2022C2A6]  DEFAULT ('N') FOR [SEMANAL]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF__TFPEVE__ADIANTAM__220B0B18]  DEFAULT ('N') FOR [ADIANTAMENTO]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF__TFPEVE__DTALTER__23F3538A]  DEFAULT (getdate()) FOR [DTALTER]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_CODCENCUS_TFPEVE]  DEFAULT (0) FOR [CODCENCUS]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_CODNAT_TFPEVE]  DEFAULT (0) FOR [CODNAT]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_PROVISAOFIN_TFPEVE]  DEFAULT (0) FOR [PROVISAOFIN]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_PENSAO_TFPEVE]  DEFAULT ('N') FOR [PENSAO]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_INCORPORA_TFPEVE]  DEFAULT ('N') FOR [INCORPORA]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_RESILICAO_TFPEVE]  DEFAULT ('N') FOR [RESILICAO]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_COMPLEMENTORESC_TFPEVE]  DEFAULT ('N') FOR [COMPLEMENTORESC]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_ATIVO_TFPEVE]  DEFAULT ('S') FOR [ATIVO]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_SANKHYA_TFPEVE]  DEFAULT ('N') FOR [SANKHYA]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_IDENTIFICACAO_TFPEVE]  DEFAULT ((0)) FOR [IDENTIFICACAO]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_TIPOINSS_TFPEVE]  DEFAULT ((0)) FOR [TIPOINSS]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_TIPOIRRF_TFPEVE]  DEFAULT ((0)) FOR [TIPOIRRF]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_FGTS_TFPEVE]  DEFAULT ('N') FOR [FGTS]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_FGTSDECTERCEIRO_TFPEVE]  DEFAULT ('N') FOR [FGTSDECTERCEIRO]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_BASEAUXILIAR_TFPEVE]  DEFAULT ('N') FOR [BASEAUXILIAR]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_PIS_TFPEVE]  DEFAULT ('N') FOR [PIS]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_ISS_TFPEVE]  DEFAULT ('N') FOR [ISS]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_INFCOMPLRAIS1_TFPEVE]  DEFAULT ((0)) FOR [INFCOMPLRAIS1]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_INFCOMPLRAIS2_TFPEVE]  DEFAULT ((0)) FOR [INFCOMPLRAIS2]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_GRRFMES_TFPEVE]  DEFAULT ('N') FOR [GRRFMES]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_GRRFMESANTERIOR_TFPEVE]  DEFAULT ('N') FOR [GRRFMESANTERIOR]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_GRRFINDENIZACAO_TFPEVE]  DEFAULT ('N') FOR [GRRFINDENIZACAO]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_BASESEFIP_TFPEVE]  DEFAULT ((0)) FOR [BASESEFIP]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_FGTSSEFIP_TFPEVE]  DEFAULT ('N') FOR [FGTSSEFIP]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_INSSSEFIP_TFPEVE]  DEFAULT ('N') FOR [INSSSEFIP]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_USADOESOCIAL_TFPEVE]  DEFAULT ('N') FOR [USADOESOCIAL]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_CONTRIBSIND_TFPEVE]  DEFAULT ('N') FOR [CONTRIBSIND]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_RUBRICADSR_TFPEVE]  DEFAULT ('N') FOR [RUBRICADSR]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_RUBRICA13_TFPEVE]  DEFAULT ('N') FOR [RUBRICA13]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_RUBRICAFERIAS_TFPEVE]  DEFAULT ('N') FOR [RUBRICAFERIAS]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_RUBRICARESCISAO_TFPEVE]  DEFAULT ('N') FOR [RUBRICARESCISAO]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_TEMCOMPLEMENTO_TFPEVE]  DEFAULT ('N') FOR [TEMCOMPLEMENTO]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_COMPLEMENTAR_TFPEVE]  DEFAULT ('N') FOR [COMPLEMENTAR]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_PLR_TFPEVE]  DEFAULT ('N') FOR [PLR]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_INTEGRACTB_TFPEVE]  DEFAULT ('S') FOR [INTEGRACTB]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_FGTSRESCISAO_TFPEVE]  DEFAULT ('N') FOR [FGTSRESCISAO]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_PENSAOSALLIQUIDO_TFPEVE]  DEFAULT ('N') FOR [PENSAOSALLIQUIDO]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_PENSAOSALBRUTO_TFPEVE]  DEFAULT ('N') FOR [PENSAOSALBRUTO]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_PENSAOSALMINIMO_TFPEVE]  DEFAULT ('N') FOR [PENSAOSALMINIMO]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_GRUPOEVENTO_TFPEVE]  DEFAULT ((0)) FOR [GRUPOEVENTO]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_USACODMOEDA_TFPEVE]  DEFAULT ('N') FOR [USACODMOEDA]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_INDENIZACAOAPI_TFPEVE]  DEFAULT ('N') FOR [INDENIZACAOAPI]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_ATIVOW_TFPEVE]  DEFAULT ('N') FOR [ATIVOW]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  CONSTRAINT [DF_INTERMITENTE_TFPEVE]  DEFAULT ('N') FOR [INTERMITENTE]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  DEFAULT ('N') FOR [CODEVEFLRES]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  DEFAULT ('N') FOR [CONSPROGFER]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  DEFAULT ((0)) FOR [DIASCPROGFER]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  DEFAULT ('01/01/1900') FOR [DTINATAPARDE]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  DEFAULT ('N') FOR [UTSALBASEARED]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  DEFAULT ('N') FOR [CODEVEFLFER]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  DEFAULT ('N') FOR [USALEI10820]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  DEFAULT ('N') FOR [PROVIDECTERSAL]
GO

ALTER TABLE [sankhya].[TFPEVE] ADD  DEFAULT ('N') FOR [PROVIFERIAS]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [FK_TFPEVE_CODCENCUS_TSICUS] FOREIGN KEY([CODCENCUS])
REFERENCES [sankhya].[TSICUS] ([CODCENCUS])
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [FK_TFPEVE_CODCENCUS_TSICUS]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [FK_TFPEVE_CODEVERRACPL] FOREIGN KEY([CODEVERRACPL])
REFERENCES [sankhya].[TFPEVE] ([CODEVENTO])
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [FK_TFPEVE_CODEVERRACPL]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [FK_TFPEVE_CODNAT_TGFNAT] FOREIGN KEY([CODNAT])
REFERENCES [sankhya].[TGFNAT] ([CODNAT])
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [FK_TFPEVE_CODNAT_TGFNAT]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [FK_TFPEVE_CODUSU_TSIUSU] FOREIGN KEY([CODUSU])
REFERENCES [sankhya].[TSIUSU] ([CODUSU])
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [FK_TFPEVE_CODUSU_TSIUSU]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [FK_TFPEVE_COMPLEMENTO_TFPEVE] FOREIGN KEY([CODEVECOMPLEMENTO])
REFERENCES [sankhya].[TFPEVE] ([CODEVENTO])
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [FK_TFPEVE_COMPLEMENTO_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [FK_TFPEVE_TFPEVE] FOREIGN KEY([CODEVERESILICAO])
REFERENCES [sankhya].[TFPEVE] ([CODEVENTO])
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [FK_TFPEVE_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [FK_TFPEVE_TFPFOR] FOREIGN KEY([CODFORM])
REFERENCES [sankhya].[TFPFOR] ([CODFORM])
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [FK_TFPEVE_TFPFOR]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [FK_TFPEVE_TSIMOE] FOREIGN KEY([CODMOEDA])
REFERENCES [sankhya].[TSIMOE] ([CODMOEDA])
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [FK_TFPEVE_TSIMOE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH NOCHECK ADD  CONSTRAINT [CKC_ACUMULADOR_TFPEVE] CHECK  (([ACUMULADOR] = 'N' or [ACUMULADOR] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_ACUMULADOR_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH NOCHECK ADD  CONSTRAINT [CKC_ADIANTAMENTO_TFPEVE] CHECK  (([ADIANTAMENTO] = 'N' or [ADIANTAMENTO] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_ADIANTAMENTO_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_ATIVO_TFPEVE] CHECK  (([ATIVO] = 'N' OR [ATIVO] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_ATIVO_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_ATIVOW_TFPEVE] CHECK  (([ATIVOW]='S' OR [ATIVOW]='N'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_ATIVOW_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_BASEAUXILIAR_TFPEVE] CHECK  (([BASEAUXILIAR] = 'N' OR [BASEAUXILIAR] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_BASEAUXILIAR_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_BASEINFREND_TFPEVE] CHECK  (([BASEINFREND] = '9' OR [BASEINFREND] = '8' OR [BASEINFREND] = '7' OR [BASEINFREND] = '6' OR [BASEINFREND] = '5' OR [BASEINFREND] = '4' OR [BASEINFREND] = '3' OR [BASEINFREND] = '2' OR [BASEINFREND] = '1' OR [BASEINFREND] = '0' OR [BASEINFREND] = 'W' OR [BASEINFREND] = 'Y' OR [BASEINFREND] = 'Z' OR [BASEINFREND] = 'H' OR [BASEINFREND] = 'V' OR [BASEINFREND] = 'Q' OR [BASEINFREND] = 'G' OR [BASEINFREND] = 'U' OR [BASEINFREND] = 'E' OR [BASEINFREND] = 'K' OR [BASEINFREND] = 'X' OR [BASEINFREND] = 'B' OR [BASEINFREND] = 'T' OR [BASEINFREND] = 'L' OR [BASEINFREND] = 'M' OR [BASEINFREND] = 'O' OR [BASEINFREND] = 'P' OR [BASEINFREND] = 'D' OR [BASEINFREND] = 'A' OR [BASEINFREND] = 'J' OR [BASEINFREND] = 'C' OR [BASEINFREND] = 'F' OR [BASEINFREND] = 'R' OR [BASEINFREND] = 'I' OR [BASEINFREND] = 'S' OR [BASEINFREND] = 'N'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_BASEINFREND_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH NOCHECK ADD  CONSTRAINT [CKC_BASELIQUIDO_TFPEVE] CHECK  (([BASELIQUIDO] = 'S' or [BASELIQUIDO] = 'N'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_BASELIQUIDO_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH NOCHECK ADD  CONSTRAINT [CKC_BASEMARGCONSIG_TFPEVE] CHECK  (([BASEMARGCONSIG] = 'F' or ([BASEMARGCONSIG] = 'O' or [BASEMARGCONSIG] = 'N')))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_BASEMARGCONSIG_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH NOCHECK ADD  CONSTRAINT [CKC_BASERAIS_TFPEVE] CHECK  (([BASERAIS] = 'N' or [BASERAIS] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_BASERAIS_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_BASESEFIP_TFPEVE] CHECK  (([BASESEFIP]>=(0) AND [BASESEFIP]<=(4)))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_BASESEFIP_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_COMPLEMENTAR_TFPEVE] CHECK  (([COMPLEMENTAR] = 'N' OR [COMPLEMENTAR] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_COMPLEMENTAR_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_COMPLEMENTORESC_TFPEVE] CHECK  (([COMPLEMENTORESC] = 'N' or [COMPLEMENTORESC] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_COMPLEMENTORESC_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_CONTRIBSIND_TFPEVE] CHECK  (([CONTRIBSIND] = 'N' OR [CONTRIBSIND] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_CONTRIBSIND_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH NOCHECK ADD  CONSTRAINT [CKC_DECTERC_TFPEVE] CHECK  (([DECTERC] = 'N' or [DECTERC] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_DECTERC_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH NOCHECK ADD  CONSTRAINT [CKC_FERIAS_TFPEVE] CHECK  (([FERIAS] = 'N' or [FERIAS] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_FERIAS_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_FGTS_TFPEVE] CHECK  (([FGTS] = 'N' OR [FGTS] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_FGTS_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_FGTSDECTERCEIRO_TFPEVE] CHECK  (([FGTSDECTERCEIRO] = 'N' OR [FGTSDECTERCEIRO] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_FGTSDECTERCEIRO_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_FGTSRESCISAO_TFPEVE] CHECK  (([FGTSRESCISAO]='N' OR [FGTSRESCISAO]='S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_FGTSRESCISAO_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_FGTSSEFIP_TFPEVE] CHECK  (([FGTSSEFIP] = 'N' OR [FGTSSEFIP] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_FGTSSEFIP_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH NOCHECK ADD  CONSTRAINT [CKC_FOLHA_TFPEVE] CHECK  (([FOLHA] = 'N' or [FOLHA] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_FOLHA_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_GRRFINDENIZACAO_TFPEVE] CHECK  (([GRRFINDENIZACAO] = 'N' OR [GRRFINDENIZACAO] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_GRRFINDENIZACAO_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_GRRFMES_TFPEVE] CHECK  (([GRRFMES] = 'N' OR [GRRFMES] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_GRRFMES_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_GRRFMESANTERIOR_TFPEVE] CHECK  (([GRRFMESANTERIOR] = 'N' OR [GRRFMESANTERIOR] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_GRRFMESANTERIOR_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_IDENTIFICACAO_TFPEVE] CHECK  (([IDENTIFICACAO]>=(0) AND [IDENTIFICACAO]<=(200)))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_IDENTIFICACAO_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_IMPHOLLERIT_TFPEVE] CHECK  (([IMPHOLLERIT] IS NULL OR ([IMPHOLLERIT] = 'R' OR [IMPHOLLERIT] = 'N' OR [IMPHOLLERIT] = 'F' OR [IMPHOLLERIT] = 'M' OR [IMPHOLLERIT] = 'S')))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_IMPHOLLERIT_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_INCORPORA_TFPEVE] CHECK  (([INCORPORA] = 'N' or [INCORPORA] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_INCORPORA_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_INCSOBREMEDIAS_TFPEVE] CHECK  (([INCSOBREMEDIAS] = 'C' OR [INCSOBREMEDIAS] = 'I' OR [INCSOBREMEDIAS] = 'E' OR [INCSOBREMEDIAS] = 'S' OR [INCSOBREMEDIAS] = 'N' OR [INCSOBREMEDIAS] IS NULL))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_INCSOBREMEDIAS_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_INDENIZACAOAPI_TFPEVE] CHECK  (([INDENIZACAOAPI]='N' OR [INDENIZACAOAPI]='S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_INDENIZACAOAPI_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_INFCOMPLRAIS1_TFPEVE] CHECK  (([INFCOMPLRAIS1]>=(0) AND [INFCOMPLRAIS1]<=(7)))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_INFCOMPLRAIS1_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_INFCOMPLRAIS2_TFPEVE] CHECK  (([INFCOMPLRAIS2]>=(0) AND [INFCOMPLRAIS2]<=(3)))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_INFCOMPLRAIS2_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_INSSSEFIP_TFPEVE] CHECK  (([INSSSEFIP] = 'N' OR [INSSSEFIP] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_INSSSEFIP_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_INTEGRACTB_TFPEVE] CHECK  (([INTEGRACTB] = 'N' OR [INTEGRACTB] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_INTEGRACTB_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_INTERMITENTE_TFPEVE] CHECK  (([INTERMITENTE]='N' OR [INTERMITENTE]='S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_INTERMITENTE_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_ISS_TFPEVE] CHECK  (([ISS] = 'N' OR [ISS] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_ISS_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_PENSAO_TFPEVE] CHECK  (([PENSAO] = 'N' or [PENSAO] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_PENSAO_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_PENSAOSALBRUTO_TFPEVE] CHECK  (([PENSAOSALBRUTO]='N' OR [PENSAOSALBRUTO]='S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_PENSAOSALBRUTO_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_PENSAOSALLIQUIDO_TFPEVE] CHECK  (([PENSAOSALLIQUIDO]='N' OR [PENSAOSALLIQUIDO]='S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_PENSAOSALLIQUIDO_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_PENSAOSALMINIMO_TFPEVE] CHECK  (([PENSAOSALMINIMO]='N' OR [PENSAOSALMINIMO]='S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_PENSAOSALMINIMO_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_PIS_TFPEVE] CHECK  (([PIS] = 'N' OR [PIS] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_PIS_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_PLR_TFPEVE] CHECK  (([PLR] = 'N' OR [PLR] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_PLR_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH NOCHECK ADD  CONSTRAINT [CKC_PROTEGIDO_TFPEVE] CHECK  (([PROTEGIDO] = 'N' or [PROTEGIDO] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_PROTEGIDO_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_PROVIDECTERSAL_TFPEVE] CHECK  (([PROVIDECTERSAL]='N' OR [PROVIDECTERSAL]='S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_PROVIDECTERSAL_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_PROVIFERIAS_TFPEVE] CHECK  (([PROVIFERIAS]='N' OR [PROVIFERIAS]='S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_PROVIFERIAS_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH NOCHECK ADD  CONSTRAINT [CKC_PROVISAOFIN_TFPEVE] CHECK  (([PROVISAOFIN] = 3 or ([PROVISAOFIN] = 2 or ([PROVISAOFIN] = 1 or [PROVISAOFIN] = 0))))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_PROVISAOFIN_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH NOCHECK ADD  CONSTRAINT [CKC_RESCISAO_TFPEVE] CHECK  (([RESCISAO] = 'N' or [RESCISAO] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_RESCISAO_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_RESILICAO_TFPEVE] CHECK  (([RESILICAO] = 'N' or [RESILICAO] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_RESILICAO_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_RUBRICA13_TFPEVE] CHECK  (([RUBRICA13] = 'N' OR [RUBRICA13] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_RUBRICA13_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_RUBRICADSR_TFPEVE] CHECK  (([RUBRICADSR] = 'N' OR [RUBRICADSR] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_RUBRICADSR_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_RUBRICAFERIAS_TFPEVE] CHECK  (([RUBRICAFERIAS] = 'N' OR [RUBRICAFERIAS] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_RUBRICAFERIAS_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_RUBRICARESCISAO_TFPEVE] CHECK  (([RUBRICARESCISAO] = 'N' OR [RUBRICARESCISAO] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_RUBRICARESCISAO_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_SANKHYA_TFPEVE] CHECK  (([SANKHYA] = 'N' OR [SANKHYA] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_SANKHYA_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH NOCHECK ADD  CONSTRAINT [CKC_SEMANAL_TFPEVE] CHECK  (([SEMANAL] = 'N' or [SEMANAL] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_SEMANAL_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_TEMCOMPLEMENTO_TFPEVE] CHECK  (([TEMCOMPLEMENTO] = 'N' OR [TEMCOMPLEMENTO] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_TEMCOMPLEMENTO_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH NOCHECK ADD  CONSTRAINT [CKC_TIPEVENTO_TFPEVE] CHECK  (([TIPEVENTO] = 0 or ([TIPEVENTO] = (-1) or [TIPEVENTO] = 1)))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_TIPEVENTO_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_TIPOINSS_TFPEVE] CHECK  (([TIPOINSS]>=(0) AND [TIPOINSS]<=(9)))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_TIPOINSS_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_TIPOIRRF_TFPEVE] CHECK  (([TIPOIRRF]>=(0) AND [TIPOIRRF]<=(8)))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_TIPOIRRF_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH NOCHECK ADD  CONSTRAINT [CKC_UNIDADE_TFPEVE] CHECK  (([UNIDADE] = 'Q' or ([UNIDADE] = 'D' or ([UNIDADE] = 'H' or [UNIDADE] = 'V'))))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_UNIDADE_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_USACODMOEDA_TFPEVE] CHECK  (([USACODMOEDA]='N' OR [USACODMOEDA]='S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_USACODMOEDA_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_USADOESOCIAL_TFPEVE] CHECK  (([USADOESOCIAL] = 'N' OR [USADOESOCIAL] = 'S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_USADOESOCIAL_TFPEVE]
GO

ALTER TABLE [sankhya].[TFPEVE]  WITH CHECK ADD  CONSTRAINT [CKC_USALEI10820_TFPEVE] CHECK  (([USALEI10820]='N' OR [USALEI10820]='S'))
GO

ALTER TABLE [sankhya].[TFPEVE] CHECK CONSTRAINT [CKC_USALEI10820_TFPEVE]
GO


